import pytest
from Test_Travel.Modules_component.Hotel.Filters.Filters import ModuleFiltersLocators
from Test_Travel.Modules_component.Hotel.Filters.Tests.TestBase import BaseTest


class TestModule1(BaseTest):
    @pytest.mark.smoke()
    def test_module_1(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        module_1_price_range = ModuleFiltersLocators(driver)
        module_1_price_range.module_1_price_range(5, -10)
        module_1_price_input_from = ModuleFiltersLocators(driver)
        module_1_price_input_from.module_1_price_input_from()
        module_1_price_input_to = ModuleFiltersLocators(driver)
        module_1_price_input_to.module_1_price_input_to()
        module_1_price_input_negative = ModuleFiltersLocators(driver)
        module_1_price_input_negative.module_1_price_input_negative()
        module_1_price_input_sql_injection = ModuleFiltersLocators(driver)
        module_1_price_input_sql_injection.module_1_price_input_sql_injection()

    @pytest.mark.smoke()
    def test_module_2(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        module_2_hotel_rating = ModuleFiltersLocators(driver)
        module_2_hotel_rating.module_2_hotel_rating()
        activate_checkbox = ModuleFiltersLocators(driver)
        activate_checkbox.activate_checkbox()
        get_checkbox_value = ModuleFiltersLocators(driver)
        get_checkbox_value.get_checkbox_value()
        get_checkbox_active_value = ModuleFiltersLocators(driver)
        get_checkbox_active_value.get_checkbox_active_value()
        perform_load_checkbox = ModuleFiltersLocators(driver)
        perform_load_checkbox.perform_load_checkbox()
        perform_load_checkbox_1 = ModuleFiltersLocators(driver)
        perform_load_checkbox_1.perform_load_checkbox_1()
        perform_load_checkbox_2 = ModuleFiltersLocators(driver)
        perform_load_checkbox_2.perform_load_checkbox_2()
        perform_load_checkbox_3 = ModuleFiltersLocators(driver)
        perform_load_checkbox_3.perform_load_checkbox_3()
        perform_load_checkbox_4 = ModuleFiltersLocators(driver)
        perform_load_checkbox_4.perform_load_checkbox_4()

    @pytest.mark.smoke()
    def test_module_3(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        hotel_rating_boxes = ModuleFiltersLocators(driver)
        hotel_rating_boxes.hotel_rating_boxes()
        hotel_rating_boxes_1 = ModuleFiltersLocators(driver)
        hotel_rating_boxes_1.hotel_rating_boxes_1()
        hotel_rating_boxes_2 = ModuleFiltersLocators(driver)
        hotel_rating_boxes_2.hotel_rating_boxes_2()
        hotel_rating_boxe_4 = ModuleFiltersLocators(driver)
        hotel_rating_boxe_4.hotel_rating_boxe_4()

    @pytest.mark.smoke()
    def test_get_price_range_module_4(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        scroll_into_view = ModuleFiltersLocators(driver)
        scroll_into_view.scroll_into_view()
        get_location = ModuleFiltersLocators(driver)
        get_location.get_location(-10, 50)
        get_location_back = ModuleFiltersLocators(driver)
        get_location_back.get_location_back(-50, 10)
        load_page = ModuleFiltersLocators(driver)
        load_page.load_page()

    @pytest.mark.smoke()
    def test_get_performance_value_from_checkboxes_module_5(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        scroll_into_view_type_of_apart = ModuleFiltersLocators(driver)
        scroll_into_view_type_of_apart.scroll_into_view_type_of_apart()
        get_performance_value_check_boxes_type_of_apart_1 = ModuleFiltersLocators(driver)
        get_performance_value_check_boxes_type_of_apart_1.get_performance_value_check_boxes_type_of_apart_1()
        get_performance_value_check_boxes_type_of_apart_2 = ModuleFiltersLocators(driver)
        get_performance_value_check_boxes_type_of_apart_2.get_performance_value_check_boxes_type_of_apart_2()
        get_performance_value_check_boxes_type_of_apart_3 = ModuleFiltersLocators(driver)
        get_performance_value_check_boxes_type_of_apart_3.get_performance_value_check_boxes_type_of_apart_3()
        get_performance_value_check_boxes_type_of_apart_4 = ModuleFiltersLocators(driver)
        get_performance_value_check_boxes_type_of_apart_4.get_performance_value_check_boxes_type_of_apart_4()
        get_performance_value_check_boxes_type_of_apart_5 = ModuleFiltersLocators(driver)
        get_performance_value_check_boxes_type_of_apart_5.get_performance_value_check_boxes_type_of_apart_5()

    @pytest.mark.smoke()
    def test_get_performance_value_from_checkboxes_module_6(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        scroll_into_view_room_amenities = ModuleFiltersLocators(driver)
        scroll_into_view_room_amenities.scroll_into_view_room_amenities()
        get_performance_load_from_amenities_checkboxes_1 = ModuleFiltersLocators(driver)
        get_performance_load_from_amenities_checkboxes_1.get_performance_load_from_amenities_checkboxes_1()
        get_performance_load_from_amenities_checkboxes_2 = ModuleFiltersLocators(driver)
        get_performance_load_from_amenities_checkboxes_2.get_performance_load_from_amenities_checkboxes_2()
        get_performance_load_from_amenities_checkboxes_3 = ModuleFiltersLocators(driver)
        get_performance_load_from_amenities_checkboxes_3.get_performance_load_from_amenities_checkboxes_3()
        get_performance_load_from_amenities_checkboxes_4 = ModuleFiltersLocators(driver)
        get_performance_load_from_amenities_checkboxes_4.get_performance_load_from_amenities_checkboxes_4()
        get_performance_load_from_amenities_checkboxes_5 = ModuleFiltersLocators(driver)
        get_performance_load_from_amenities_checkboxes_5.get_performance_load_from_amenities_checkboxes_5()

    @pytest.mark.smoke()
    def test_get_performance_value_from_checkboxes_module_7(self, driver):
        driver.get('https://www.votpusk.ru/hotels/russia/moscow')
        close_modal = ModuleFiltersLocators(driver)
        close_modal.Close_modal()
        scroll_into_view_hotel_amenities = ModuleFiltersLocators(driver)
        scroll_into_view_hotel_amenities.scroll_into_view_hotel_amenities()
        get_performance_load_from_hotel_amenities_1 = ModuleFiltersLocators(driver)
        get_performance_load_from_hotel_amenities_1.get_performance_load_from_hotel_amenities_1()
        get_performance_load_from_hotel_amenities_2 = ModuleFiltersLocators(driver)
        get_performance_load_from_hotel_amenities_2.get_performance_load_from_hotel_amenities_2()
        get_performance_load_from_hotel_amenities_3 = ModuleFiltersLocators(driver)
        get_performance_load_from_hotel_amenities_3.get_performance_load_from_hotel_amenities_3()
        get_performance_load_from_hotel_amenities_4 = ModuleFiltersLocators(driver)
        get_performance_load_from_hotel_amenities_4.get_performance_load_from_hotel_amenities_4()
        get_performance_load_from_hotel_amenities_5 = ModuleFiltersLocators(driver)
        get_performance_load_from_hotel_amenities_5.get_performance_load_from_hotel_amenities_5()