from Test_Travel.Votpusk_fuctional_automation_test.VOTPUSK.Train.Train_obtain_page.Filters.filters import FiltersTrainLocator
from Test_Travel.Votpusk_fuctional_automation_test.VOTPUSK.Train.train_form.train_schandual import TrainCheckingTrainLocators
from Test_Travel.Votpusk_fuctional_automation_test.VOTPUSK.Train.sliders.sliders import SlidersTrainLocator
from Test_Travel.Votpusk_fuctional_automation_test.VOTPUSK.Train.test.testbase import BaseTest
from Test_Travel.Votpusk_fuctional_automation_test.VOTPUSK.Train.config.configuration import TestData
from Test_Travel.Votpusk_fuctional_automation_test.VOTPUSK.Train.Train_obtain_page.Form.obtain_form import ObtainFormLocators


class TestTrain(BaseTest):

    def test_schedule_form(self, driver):
        driver.get(TestData.URL)
        assert_schedule_button = TrainCheckingTrainLocators(driver)
        assert_schedule_button.assert_schedule_button()
        assert_by_routs_form = TrainCheckingTrainLocators(driver)
        assert_by_routs_form.assert_by_routs_form()
        assert_by_routs_form_to = TrainCheckingTrainLocators(driver)
        assert_by_routs_form_to.assert_by_routs_form_to()
        assert_select_random_date_day = TrainCheckingTrainLocators(driver)
        assert_select_random_date_day.assert_select_random_date_day()
        assert_select_random_date_month = TrainCheckingTrainLocators(driver)
        assert_select_random_date_month.assert_select_random_date_month()
        assert_select_random_date_year = TrainCheckingTrainLocators(driver)
        assert_select_random_date_year.assert_select_random_date_year()
        assert_search_by_routs_button = TrainCheckingTrainLocators(driver)
        assert_search_by_routs_button.assert_search_by_routs_button()

    def test_by_station(self, driver):
        driver.get(TestData.URL)
        assert_click_by_station_button = TrainCheckingTrainLocators(driver)
        assert_click_by_station_button.assert_click_by_station_button()
        assert_by_station_input = TrainCheckingTrainLocators(driver)
        assert_by_station_input.assert_by_station_input()
        assert_select_random_date_station_day = TrainCheckingTrainLocators(driver)
        assert_select_random_date_station_day.assert_select_random_date_station_day()
        assert_select_random_date_station_month = TrainCheckingTrainLocators(driver)
        assert_select_random_date_station_month.assert_select_random_date_station_month()
        assert_select_random_date_station_year = TrainCheckingTrainLocators(driver)
        assert_select_random_date_station_year.assert_select_random_date_station_year()
        assert_station_search_button = TrainCheckingTrainLocators(driver)
        assert_station_search_button.assert_station_search_button()

    def test_train_by_number(self, driver):
        driver.get(TestData.URL)
        assert_by_train_number = TrainCheckingTrainLocators(driver)
        assert_by_train_number.assert_by_train_number()
        assert_search_by_number_form = TrainCheckingTrainLocators(driver)
        assert_search_by_number_form.assert_search_by_number_form()

    def test_obtain_tickets(self, driver):
        driver.get(TestData.URL)
        assert_obtain_button = TrainCheckingTrainLocators(driver)
        assert_obtain_button.assert_obtain_button()
        assert_click_obtain_tickets = TrainCheckingTrainLocators(driver)
        assert_click_obtain_tickets.assert_click_obtain_tickets()
        assert_obtain_form = TrainCheckingTrainLocators(driver)
        assert_obtain_form.assert_obtain_form()
        assert_obtain_to = TrainCheckingTrainLocators(driver)
        assert_obtain_to.assert_obtain_to()
        assert_select_randomly_date_from = TrainCheckingTrainLocators(driver)
        assert_select_randomly_date_from.assert_select_randomly_date_from()
        assert_obtain_next_date = TrainCheckingTrainLocators(driver)
        assert_obtain_next_date.assert_obtain_next_date()
        assert_select_randomly_date_to = TrainCheckingTrainLocators(driver)
        assert_select_randomly_date_to.assert_select_randomly_date_to()
        assert_obtain_search_button = TrainCheckingTrainLocators(driver)
        assert_obtain_search_button.assert_obtain_search_button()

    # Популярные направления
    def test_popular_destination(self, driver):
        driver.get(TestData.URL)
        assert_scroll_into_view_popular_destination = SlidersTrainLocator(driver)
        assert_scroll_into_view_popular_destination.assert_scroll_into_view_popular_destination()
        assert_popular_destination_block = SlidersTrainLocator(driver)
        assert_popular_destination_block.assert_popular_destination_block()
        assert_cities_blocks = SlidersTrainLocator(driver)
        assert_cities_blocks.assert_cities_blocks()
        assert_arrow_links = SlidersTrainLocator(driver)
        assert_arrow_links.assert_arrow_links()
        assert_show_all_destination_link = SlidersTrainLocator(driver)
        assert_show_all_destination_link.assert_show_all_destination_link()

    def test_obtain_tickets_module(self, driver):
        driver.get(TestData.URL)
        assert_scroll_into_view_obtain_tickets = SlidersTrainLocator(driver)
        assert_scroll_into_view_obtain_tickets.assert_scroll_into_view_obtain_tickets()
        assert_train_blocks = SlidersTrainLocator(driver)
        assert_train_blocks.assert_train_blocks()
        assert_read_obtain_tickets_links = SlidersTrainLocator(driver)
        assert_read_obtain_tickets_links.assert_read_obtain_tickets_links()

    def test_comment_section(self, driver):
        driver.get(TestData.URL)
        assert_scroll_into_view_comment_section = SlidersTrainLocator(driver)
        assert_scroll_into_view_comment_section.assert_scroll_into_view_comment_section()
        assert_comment_section = SlidersTrainLocator(driver)
        assert_comment_section.assert_comment_section()
        assert_write_comment_button = SlidersTrainLocator(driver)
        assert_write_comment_button.assert_write_comment_button()

    def test_faq_module(self, driver):
        driver.get(TestData.URL)
        assert_scroll_into_view_faq = SlidersTrainLocator(driver)
        assert_scroll_into_view_faq.assert_scroll_into_view_faq()
        assert_faq_block = SlidersTrainLocator(driver)
        assert_faq_block.assert_faq_block()
        assert_show_all_section = SlidersTrainLocator(driver)
        assert_show_all_section.assert_show_all_section()

    def test_obtain_ticket_section(self, driver):
        driver.get(TestData.PRICE_URL)
        assert_form_container = ObtainFormLocators(driver)
        assert_form_container.assert_form_container()
        assert_is_filed_from_present = ObtainFormLocators(driver)
        assert_is_filed_from_present.assert_is_filed_from_present()
        assert_is_field_to_present = ObtainFormLocators(driver)
        assert_is_field_to_present.assert_is_field_to_present()
        assert_scroll_into_view = ObtainFormLocators(driver)
        assert_scroll_into_view.assert_scroll_into_view()
        open_calendar_from = ObtainFormLocators(driver)
        open_calendar_from.open_calendar_from()
        assert_select_randomly_date_to = ObtainFormLocators(driver)
        assert_select_randomly_date_to.assert_select_randomly_date_to()
        open_calendar_to = ObtainFormLocators(driver)
        open_calendar_to.open_calendar_to()
        assert_select_randomly_date_from = ObtainFormLocators(driver)
        assert_select_randomly_date_from.assert_select_randomly_date_from()
        assert_form_button = ObtainFormLocators(driver)
        assert_form_button.assert_form_button()

    # Filters
    def test_filters(self, driver):
        driver.get(TestData.PRICE_URL)
        is_page_loaded = FiltersTrainLocator(driver)
        is_page_loaded.is_page_loaded()
        scroll_into_filters_view = FiltersTrainLocator(driver)
        scroll_into_filters_view.scroll_into_filters_view()
        assert_filters_container = FiltersTrainLocator(driver)
        assert_filters_container.assert_filters_container()
        assert_cost_filed_from = FiltersTrainLocator(driver)
        assert_cost_filed_from.assert_cost_filed_from()
        assert_cost_field_to = FiltersTrainLocator(driver)
        assert_cost_field_to.assert_cost_field_to()
        assert_checkboxes_plats_card = FiltersTrainLocator(driver)
        assert_checkboxes_plats_card.assert_checkboxes_plats_card()
        assert_checkboxes_coupe = FiltersTrainLocator(driver)
        assert_checkboxes_coupe.assert_checkboxes_coupe()
        assert_checkboxes_seat_reserved = FiltersTrainLocator(driver)
        assert_checkboxes_seat_reserved.assert_checkboxes_seat_reserved()
        assert_checkboxes_public = FiltersTrainLocator(driver)
        assert_checkboxes_public.assert_checkboxes_public()
        assert_checkboxes_priority = FiltersTrainLocator(driver)
        assert_checkboxes_priority.assert_checkboxes_priority()
        assert_checkboxes_lux = FiltersTrainLocator(driver)
        assert_checkboxes_lux.assert_checkboxes_lux()
        assert_checkboxes_aside = FiltersTrainLocator(driver)  # Places
        assert_checkboxes_aside.assert_checkboxes_aside()
        assert_checkboxes_men_coupe = FiltersTrainLocator(driver)
        assert_checkboxes_men_coupe.assert_checkboxes_men_coupe()
        assert_checkboxes_down_seats = FiltersTrainLocator(driver)
        assert_checkboxes_down_seats.assert_checkboxes_down_seats()
        assert_checkboxes_female_seats = FiltersTrainLocator(driver)
        assert_checkboxes_female_seats.assert_checkboxes_female_seats()
        assert_checkboxes_upside_side = FiltersTrainLocator(driver)
        assert_checkboxes_upside_side.assert_checkboxes_upside_side()
        assert_checkboxes_perfect = FiltersTrainLocator(driver)
        assert_checkboxes_perfect.assert_checkboxes_perfect()   # Rating
        assert_checkboxes_excellent = FiltersTrainLocator(driver)
        assert_checkboxes_excellent.assert_checkboxes_excellent()
        assert_checkboxes_good = FiltersTrainLocator(driver)
        assert_checkboxes_good.assert_checkboxes_good()    # Services
        assert_checkboxes_food_staff = FiltersTrainLocator(driver)
        assert_checkboxes_food_staff.assert_checkboxes_food_staff()
        assert_checkboxes_fpwk = FiltersTrainLocator(driver)
        assert_checkboxes_fpwk.assert_checkboxes_fpwk()
        assert_checkboxes_air_conditioner = FiltersTrainLocator(driver)
        assert_checkboxes_air_conditioner.assert_checkboxes_air_conditioner()
        assert_checkboxes_tvmedia = FiltersTrainLocator(driver)
        assert_checkboxes_tvmedia.assert_checkboxes_tvmedia()
        assert_checkboxes_tv = FiltersTrainLocator(driver)
        assert_checkboxes_tv.assert_checkboxes_tv()
        assert_checkboxes_sanitary_kit = FiltersTrainLocator(driver)
        assert_checkboxes_sanitary_kit.assert_checkboxes_sanitary_kit()
        assert_checkboxes_bed_set = FiltersTrainLocator(driver)
        assert_checkboxes_bed_set.assert_checkboxes_bed_set()
        assert_checkboxes_bio_toilet = FiltersTrainLocator(driver)
        assert_checkboxes_bio_toilet.assert_checkboxes_bio_toilet()
        assert_checkboxes_transfer = FiltersTrainLocator(driver)
        assert_checkboxes_transfer.assert_checkboxes_transfer()
        assert_checkboxes_press = FiltersTrainLocator(driver)
        assert_checkboxes_press.assert_checkboxes_press()
        assert_checkboxes_pet_transfer = FiltersTrainLocator(driver)
        assert_checkboxes_pet_transfer.assert_checkboxes_pet_transfer()
        assert_checkboxes_no_pets = FiltersTrainLocator(driver)
        assert_checkboxes_no_pets.assert_checkboxes_no_pets()
        assert_checkboxes_refundable_ticket = FiltersTrainLocator(driver)
        assert_checkboxes_refundable_ticket.assert_checkboxes_refundable_ticket()
        assert_checkboxes_non_refundable_ticket = FiltersTrainLocator(driver)
        assert_checkboxes_non_refundable_ticket.assert_checkboxes_non_refundable_ticket()

